---
- name: Install & Configure Libreswan, FRR for Site-to-Site IPSec VPN to OCI
  hosts: all
  become: true
  vars_files:
    - ./vars.yml

  tasks:
    - name: Put SELinux in permissive mode, only logging actions that would otherwise have been blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    # Install required packages
    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - libreswan
          - frr
        state: present

    # Enable IP forwarding
    - name: Configure IP forwarding
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: true # sysctl -p
      loop:
        # "net.ipv4.ip_forward=1" enables IP forwarding on the system. When set to 1, it allows the Linux machine to act as a router,
        # forwarding IP packets from one network interface to another
        - { name: 'net.ipv4.ip_forward', value: '1' }

        # as this node is going to act as CPE/BGP router, we disable sending and receiving of ICMP redirect messages, which alter kernel routes
        - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.send_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.{{ ansible_default_ipv4.interface }}.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.{{ ansible_default_ipv4.interface }}.send_redirects', value: '0' }

    - name: Configure Libreswan ipsec.conf
      ansible.builtin.copy:
        content: |
          config setup
              plutodebug=all
              plutostderrlog=/var/log/pluto.log
              protostack=auto

          conn oracle-tunnel-1
              left={{ cpe_local_private_ip }}
              leftid={{ cpe_public_ipv4 }} # 1-1 NATing
              right={{ oracle_headend_tun_a }}
              rightid={{ oracle_headend_tun_a }}
              authby=secret
              leftsubnet=0.0.0.0/0
              rightsubnet=0.0.0.0/0
              auto=start
              mark=5/0xffffffff
              vti-interface={{ vti_a }}
              leftvti={{ vti_a_local_ip }}/30
              vti-routing=no
              ikev2=yes
              ike=aes_cbc256-sha2_384;modp1536
              phase2alg=aes_gcm256;modp1536
              encapsulation=yes
              ikelifetime=28800s
              salifetime=3600s
              pfs=yes

          conn oracle-tunnel-2
              left={{ cpe_local_private_ip }}
              leftid={{ cpe_public_ipv4 }} # 1-1 NATing
              right={{ oracle_headend_tun_b }}
              rightid={{ oracle_headend_tun_b }}
              authby=secret
              leftsubnet=0.0.0.0/0
              rightsubnet=0.0.0.0/0
              auto=start
              mark=6/0xffffffff
              vti-interface={{ vti_b }}
              leftvti={{ vti_b_local_ip }}/30
              vti-routing=no
              ikev2=yes
              ike=aes_cbc256-sha2_384;modp1536
              phase2alg=aes_gcm256;modp1536
              encapsulation=yes
              ikelifetime=28800s
              salifetime=3600s
              pfs=yes
        dest: /etc/ipsec.d/oci-ipsec.conf
        mode: '0600'

    - name: Configure Libreswan ipsec.secrets
      ansible.builtin.copy:
        content: |
          {{ cpe_public_ipv4 }} {{ oracle_headend_tun_a }} : PSK "{{ psk_tun_a }}"
          {{ cpe_public_ipv4 }} {{ oracle_headend_tun_b }} : PSK "{{ psk_tun_b }}"
        dest: /etc/ipsec.d/oci-ipsec.secrets
        mode: '0600'

    - name: Enable and Start ipsec service
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: restarted
      loop:
        - ipsec

    - name: Turn on bgpd deamon config in FRR
      ansible.builtin.lineinfile:
        path: /etc/frr/daemons
        regexp: 'bgpd=no'
        line: 'bgpd=yes'
        mode: '0600'

    - name: Configure FRR bgpd.conf
      ansible.builtin.copy:
        content: |
          hostname {{ ansible_hostname }}
          log file /var/log/frr/frr.log
          no ipv6 forwarding
          router bgp {{ bgp_asn_local }}
           bgp router-id {{ bgp_router_id }}
           no bgp ebgp-requires-policy
           no bgp network import-check
           neighbor {{ vti_a_remote_ip }} remote-as {{ bgp_asn_remote }}
           neighbor {{ vti_a_remote_ip }} ebgp-multihop 255
           neighbor {{ vti_a_remote_ip }} timers 6 18
           neighbor {{ vti_a_remote_ip }} next-hop-self
           neighbor {{ vti_a_remote_ip }} activate
           neighbor {{ vti_b_remote_ip }} remote-as {{ bgp_asn_remote }}
           neighbor {{ vti_b_remote_ip }} ebgp-multihop 255
           neighbor {{ vti_b_remote_ip }} timers 6 18
           neighbor {{ vti_b_remote_ip }} next-hop-self
           neighbor {{ vti_b_remote_ip }} activate
           neighbor {{ gobgp_bgp_speaker_ip }} remote-as 65005
           neighbor {{ gobgp_bgp_speaker_ip }} ebgp-multihop 255
           neighbor {{ gobgp_bgp_speaker_ip }} timers 6 18
           neighbor {{ gobgp_bgp_speaker_ip }} next-hop-self
           neighbor {{ gobgp_bgp_speaker_ip }} activate
           address-family ipv4 unicast
            network {{ cpe_onprem_vcn_cidr }}
            neighbor {{ vti_a_remote_ip }} soft-reconfiguration inbound
            neighbor {{ vti_a_remote_ip }} route-map ALLOW-ALL in
            neighbor {{ vti_a_remote_ip }} route-map BGP-ADVERTISE-OUT out
            neighbor {{ vti_b_remote_ip }} soft-reconfiguration inbound
            neighbor {{ vti_b_remote_ip }} route-map ALLOW-ALL in
            neighbor {{ vti_b_remote_ip }} route-map BGP-ADVERTISE-OUT out
            neighbor {{ gobgp_bgp_speaker_ip }} soft-reconfiguration inbound
            neighbor {{ gobgp_bgp_speaker_ip }} route-map ALLOW-ALL in
            neighbor {{ gobgp_bgp_speaker_ip }} route-map BGP-ADVERTISE-OUT out
           exit-address-family
           ip prefix-list BGP-LIBERAL seq 10 permit 0.0.0.0/0
           route-map BGP-ADVERTISE-OUT permit 10
             match ip address prefix-list BGP-LIBERAL
           exit
           route-map ALLOW-ALL permit 100
        dest: /etc/frr/frr.conf
        mode: '0600'

    - name: Allow IPSec and BGP traffic in firewall
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 500/udp
        - 4500/udp
        - 179/tcp  # BGP port

    - name: Allow ESP protocol in firewall
      ansible.posix.firewalld:
        rich_rule: 'rule protocol value="esp" accept'
        permanent: true
        state: enabled

    - name: Reload firewall to apply changes
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded

    - name: Disable firewalld # keeping for ICMP pings for testing
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: Enable and Start ipsec and frr services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: restarted
      loop:
        - ipsec
        - frr

    - name: Get Status, just for information
      ansible.builtin.shell: |
        sleep 10
        ifconfig
        ip route show
        systemctl status ipsec
        systemctl status frr
        vtysh -c "show running-config"
        vtysh -c "sh run"
        vtysh -c "sh bgp sum"
        cat /etc/frr/vtysh.conf
        cat /etc/frr/frr.conf
        vtysh -c "show ip bgp neighbors"
        cat /var/log/frr/frr.log
      register: tunnel_activation_result
      changed_when: false

    - name: Display tunnel activation output
      ansible.builtin.debug:
        var: tunnel_activation_result
